name: ai-stack

services:
  rocm:
    image: vladchernikov/rocm:nightly-gtx110x
    profiles: [build]
    build:
      context: .
      target: rocm
      args:
        ROCM_DOWNLOADS_URL: https://rocm.nightlies.amd.com/v2/gfx110X-all/

  pytorch:
    image: vladchernikov/rocm:nightly-gtx110x-pytorch
    profiles: [build]
    build:
      context: .
      target: pytorch
      args:
        ROCM_DOWNLOADS_URL: https://rocm.nightlies.amd.com/v2/gfx110X-all/

  comfyui:
    image: vladchernikov/rocm:nightly-gtx110x-comfyui
    build:
      context: .
      target: comfyui
      args:
        ROCM_DOWNLOADS_URL: https://rocm.nightlies.amd.com/v2/gfx110X-all/
    container_name: comfyui
    restart: unless-stopped
    init: true
    ipc: host
    # use host or bridge network
    network_mode: "host"
    # ports:
    #   - "8188:8188"
    devices:
      - /dev/kfd
      - /dev/dri
    security_opt:
      - seccomp=unconfined
    volumes:
      - ./volumes/comfyui/models:/opt/ComfyUI/models
      - ./volumes/comfyui/input:/opt/ComfyUI/input
      - ./volumes/comfyui/output:/opt/ComfyUI/output
      - ./volumes/comfyui/custom_nodes:/opt/ComfyUI/custom_nodes
      - ./volumes/comfyui/user:/opt/ComfyUI/user
    environment:
      ROCM_SDK_LIB: "/root/.venv/lib/python3.14/site-packages/_rocm_sdk_devel/lib"
      LIBRARY_PATH: "/root/.venv/lib/python3.14/site-packages/_rocm_sdk_devel/lib"
      LD_LIBRARY_PATH: "/root/.venv/lib/python3.14/site-packages/_rocm_sdk_devel/lib:/opt/rocm/lib:/opt/rocm/lib64"
    command:
      - python
      - main.py
      - --use-sage-attention
      - --lowvram
      - --listen
      - 0.0.0.0
      - --port
      - "8188"

  ollama:
    image: ollama/ollama:rocm
    container_name: ollama
    restart: unless-stopped
    init: true
    # use host or bridge network
    network_mode: "host"
    # ports:
    #   - "11434:11434"
    devices:
      - /dev/kfd
      - /dev/dri
    environment:
      HSA_OVERRIDE_GFX_VERSION: "11.0.2"
      OLLAMA_NUM_PARALLEL: "1"
      OLLAMA_MAX_LOADED_MODELS: "1"
      # OLLAMA_VULKAN: "1"
      # ROCR_VISIBLE_DEVICES: "0"
      OLLAMA_FLASH_ATTENTION: "1"
      GGML_HIP_FORCE_MMQ: "1"
      GGML_HIP_USE_GRAPHS: "0"
      OLLAMA_BATCH_SIZE: "512"
      OLLAMA_CONTEXT_LENGTH: "8192"
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    volumes:
      - ./volumes/ollama:/root/.ollama

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    init: true
    depends_on:
      ollama:
        condition: service_healthy
    # use host or bridge network
    network_mode: "host"
    # ports:
    #   - "8080:8080"
    environment:
      # if host network
      OLLAMA_BASE_URL: http://localhost:11434
      # if bridge network
      # OLLAMA_BASE_URL: http://ollama:11434
    volumes:
      - ./volumes/open-webui:/app/backend/data
